name: Deploy to GitHub Pages

on:
  push:
    branches:
      [master]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.101'

    - name: Publish .NET Core Project
      run: dotnet publish Crude/Crude.csproj -c Release -o out --nologo

    - name: Change base - tag in index.html from / to Crude
      run: sed - i 's/<base href="\/" \/>/<base href="\/Crude\/" \/>/g' out/wwwroot/index.html

    - name: copy index.html to 404.html
      run: cp out/wwwroot/index.html out/wwwroot/404.html

      # Allow files and folders starting with an underscore
    - name: Add .nojekyll file
      run: touch out/wwwroot/.nojekyll

    - name: Commit wwwroot to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./out/wwwroot
